services:
  web:
    build: .
    ports:
      - 4200:4200
    depends_on:
      - sqldata

  sqldata:
    build:
      context: ./database
    environment:
      - SA_PASSWORD=Senha123
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    container_name: sql-server